.github/codeowners

---
- [Frontend](https://quickstart-openshift-backends-10-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-backends-10-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-backends-10-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-backends-10-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-backends-10-backend-go.apps.silver.devops.gov.bc.ca) …

Codeowners

---

backend-java/pom.xml

---
- [Frontend](https://quickstart-openshift-backends-7-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-backends-7-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-backends-7-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-backends-7-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-backends-7-backend-go.apps.silver.devops.gov.bc.ca)
- [Tests Workflow](https://github.com/bcgov/quickstart-openshift-backends/actions/wo …

Update quarkus to latest version

---

.github/workflows/merge.yml

---
- [Frontend](https://quickstart-openshift-backends-15-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-backends-15-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-backends-15-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-backends-15-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-backends-15-backend-go.apps.silver.devops.gov.bc.ca) …

ci: clip triggers from merge workflow

---

.github/workflows/pr-open.yml

---
- [Frontend](https://quickstart-openshift-backends-17-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-backends-17-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-backends-17-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-backends-17-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-backends-17-backend-go.apps.silver.devops.gov.bc.ca) …

ci: database and frontend builds

---

.github/workflows/merge.yml

---
- [Frontend](https://quickstart-openshift-backends-18-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-backends-18-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-backends-18-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-backends-18-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-backends-18-backend-go.apps.silver.devops.gov.bc.ca) …

fix: prod deployments

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml

---
- [Frontend](https://quickstart-openshift-backends-21-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-backends-21-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-backends-21-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-backends-21-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-backends-21-backend-go.apps.silver.devops.gov.bc.ca) …

deps: bump deployer action

---

backend-java/.dockerignore
backend-java/Dockerfile

---
- [Frontend](https://quickstart-openshift-backends-23-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-backends-23-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-backends-23-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-backends-23-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-backends-23-backend-go.apps.silver.devops.gov.bc.ca) …

deps: quarkus graalvmce build base

---

backend-py/db/migrations/V1.0.0__init.sql
backend-py/src/v1/models/entities.py
backend-py/src/v1/models/model.py

---
- [Frontend](https://quickstart-openshift-backends-25-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-backends-25-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-backends-25-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-backends-25-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-backends-25-backend-go.apps.silver.devops.gov.bc.ca) …

feat: general cleanup, flyway consistency

---

.github/workflows/pentests.yml

---
- [Frontend](https://quickstart-openshift-backends-31-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-backends-31-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-backends-31-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-backends-31-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-backends-31-backend-go.apps.silver.devops.gov.bc.ca) …

feat scheduled pen tests

---

.github/workflows/pr-open.yml

---
- [Frontend](https://quickstart-openshift-backends-35-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-backends-35-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-backends-35-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-backends-35-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-backends-35-backend-go.apps.silver.devops.gov.bc.ca) …

bug: nab stale parameter

---

.github/workflows/pr-open.yml

---
- [Frontend](https://quickstart-openshift-backends-36-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-backends-36-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-backends-36-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-backends-36-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-backends-36-backend-go.apps.silver.devops.gov.bc.ca) …

Revert "bug: nab stale parameter (#35)"

---

.github/workflows/pr-open.yml

---
- [Backend](https://quickstart-openshift-backends-69-backend.apps.silver.devops.gov.bc.ca)
- [Backend-java](https://quickstart-openshift-backends-69-backend-java.apps.silver.devops.gov.bc.ca)
- [Backend-py](https://quickstart-openshift-backends-69-backend-py.apps.silver.devops.gov.bc.ca)
- [Backend-go](https://quickstart-openshift-backends-69-backend-go.apps.silver.devops.gov.bc.ca)
- [Tests Workflow](https://github.com/bcgov/quickstart-openshift-backends/actions/workflows/tests.yml)
After merge, new images are promoted to:
- [Main Merge …

ci: remove unnecessary build param

---

.github/workflows/merge.yml
charts/quickstart-openshift-backends/templates/backendPy/templates/deployment.yaml

---
- [Java](https://quickstart-openshift-backends-104-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-104-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-104-backendGo.apps.silver.devops.gov.bc.ca)

fix: schema for python and tag names

---

charts/quickstart-openshift-backends/templates/secret.yaml

---
- [Java](https://quickstart-openshift-backends-106-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-106-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-106-backendGo.apps.silver.devops.gov.bc.ca)

fix: py api env var

---

backend-java/pom.xml

---
- [Java](https://quickstart-openshift-backends-143-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-143-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-143-backendGo.apps.silver.devops.gov.bc.ca)

chore(backend-java): version upgrade

---

renovate.json

---
- [Java](https://quickstart-openshift-backends-176-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-176-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-176-backendGo.apps.silver.devops.gov.bc.ca)

chore(ci): Renovate non-major update rules

---

.github/workflows/analysis.yml
backend-java/pom.xml

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
---
- [Java](https://quickstart-openshift-backends-181-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-181-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-181-backendGo.apps.silver.devops.gov.bc.ca)
- [Analysis …

chore(deps): java 21 pom

---

.github/workflows/analysis.yml
.github/workflows/pr-open.yml
.github/workflows/pr-validate.yml

---
- [Java](https://quickstart-openshift-backends-221-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-221-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-221-backendGo.apps.silver.devops.gov.bc.ca)

chore(ci): consistent results jobs

---

.github/workflows/analysis.yml
backend-java/Dockerfile
backend-java/pom.xml

---
- [Java](https://quickstart-openshift-backends-256-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-256-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-256-backendGo.apps.silver.devops.gov.bc.ca)

chore: update to JDK 23

---

README.md

Archive notice.
---
- [Java](https://quickstart-openshift-backends-259-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-259-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-259-backendGo.apps.silver.devops.gov.bc.ca)

docs: archiving

---

.github/workflows/analysis.yml
.github/workflows/pr-open.yml

---
- [Java](https://quickstart-openshift-backends-271-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-271-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-271-backendGo.apps.silver.devops.gov.bc.ca)

ci: catch canceled in results job

---

backend-py/Dockerfile

Tiny change to make CodeQL happy.
@mishraomp This took an embarassingly long time to solve.  :P
---
- [Java](https://quickstart-openshift-backends-273-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-273-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-273-backendGo.apps.silver.devops.gov.bc.ca)

ci: Dockerfile json args recommended

---

.github/workflows/analysis.yml
.github/workflows/pr-open.yml

---
- [Java](https://quickstart-openshift-backends-276-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-276-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-276-backendGo.apps.silver.devops.gov.bc.ca)

ci(fix): catch canceled in results job

---

backend-py/Dockerfile
docker-compose.yml

- drop curl
- distroless (too many issues, too complex)
---
- [Java](https://quickstart-openshift-backends-275-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-275-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-275-backendGo.apps.silver.devops.gov.bc.ca)

ci: misc adjustments for python

---

charts/quickstart-openshift-backends/templates/backendGo/templates/deployment.yaml
charts/quickstart-openshift-backends/templates/backendJava/templates/deployment.yaml
charts/quickstart-openshift-backends/templates/backendPy/templates/deployment.yaml
charts/quickstart-openshift-backends/values.yaml

---
- [Java](https://quickstart-openshift-backends-290-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-290-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-290-backendGo.apps.silver.devops.gov.bc.ca)

chore: remove limits

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml

---
- [Java](https://quickstart-openshift-backends-294-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-294-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-294-backendGo.apps.silver.devops.gov.bc.ca)

chore(ci): actions moved to bcgov org

---

.github/workflows/merge.yml
.github/workflows/pentests.yml

---
- [Java](https://quickstart-openshift-backends-295-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-295-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-295-backendGo.apps.silver.devops.gov.bc.ca)

chore(ci): use GH runner ubuntu-24.04

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml

---
- [Java](https://quickstart-openshift-backends-300-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-300-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-300-backendGo.apps.silver.devops.gov.bc.ca)

fix: merge pipeline

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml
charts/crunchy/values.yml

---
- [Java](https://quickstart-openshift-backends-303-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-303-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-303-backendGo.apps.silver.devops.gov.bc.ca)

fix: remove cleanup until a better solution found

---

charts/app/Chart.yaml
charts/app/values.yaml

---
- [Java](https://quickstart-openshift-backends-311-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-311-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-311-backendGo.apps.silver.devops.gov.bc.ca)

chore: remove bitnami pg elements, which triggers renovate prs

---

.github/workflows/.deploy.yml

---
- [Java](https://quickstart-openshift-backends-317-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-317-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-317-backendGo.apps.silver.devops.gov.bc.ca)

chore: update crunchy action to adhere to openshift security

---

renovate.json

---
- [Java](https://quickstart-openshift-backends-319-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-319-backendPy.apps.silver.devops.gov.bc.ca)
- [Go](https://quickstart-openshift-backends-319-backendGo.apps.silver.devops.gov.bc.ca)

chore(ci): renovate minimumReleaseAge=0

---

README.md

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
---
- [Java](https://quickstart-openshift-backends-336-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-336-backendPy.apps.silver.devops.gov.bc.ca)
After merge, new images …

docs: fixed link to QSOS

---

.github/workflows/merge.yml

---
- [Java](https://quickstart-openshift-backends-337-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-337-backendPy.apps.silver.devops.gov.bc.ca)

chore(ci): change main merge prerequisites

---

.gitattributes
.github/workflows/.deploy.yml
backend-java/pom.xml
backend-java/src/main/resources/application.properties
backend-java/src/test/java/ca/bc/gov/nrs/api/helpers/TestHelper.java
backend-java/src/test/resources/application.properties

---
- [Java](https://quickstart-openshift-backends-378-backendJava.apps.silver.devops.gov.bc.ca)
- [Py](https://quickstart-openshift-backends-378-backendPy.apps.silver.devops.gov.bc.ca)

fix: java build issues on dependency upgrades
